name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test_group: [1, 2, 3]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          echo "build-${{ matrix.test_group }}"

  build2:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test_group: [1, 2, 3]

    steps:
      - uses: actions/checkout@v4

      - name: Build2
        run: |
          echo "build2-${{ matrix.test_group }}"

  BurgerKing:
    needs: [build, build2]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run BurgerKing
        run: python .github/scripts/burgerKing.py
